import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";

export default function Home() {
  const { t } = useTranslation("home");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("welcome")}</h1>

        <ul className={styles.list}>
          <li>
            <Link href="/server-rendered">{t("serverRendered")}</Link>
          </li>
          <li>
            <Link href="/client-rendered">{t("clientRendered")}</Link>
          </li>
          <li>
            <Link href="/api-request">{t("apiRequest")}</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
